#!/usr/bin/env bash
set -ex

echo "Compiling"
cd paillier && make compile
cd ..

echo "Running 1k"
export ID=1
cd paillier && make run ID=${ID}
cp alice/decryptedProb${ID}.data ..
# cp time_memory_encryption.tmp /results/time_memory_encryption${ID}.txt
# cp time_memory_query.tmp /results/time_memory_query${ID}.txt
# cp time_memory_decryption.tmp /results/time_memory_decryption${ID}.txt
cd ..
python3 format.py decryptedProb${ID}.tmp ${ID}k_proba_formatted.tmp
python3 evaluation.py -i ${ID}k_proba_formatted.tmp -t YTrue_${ID}k_formatted.txt -o /results/auc_test_${ID}k.png

echo "Running 10k"
export ID=10
cd paillier && make ID=${ID}
cp alice/decryptedProb${ID}.data ..
# cp time_memory_encryption.tmp /results/time_memory_encryption${ID}.txt
# cp time_memory_query.tmp /results/time_memory_query${ID}.txt
# cp time_memory_decryption.tmp /results/time_memory_decryption${ID}.txt
cd ..
python3 format.py decryptedProb${ID}.tmp ${ID}k_proba_formatted.tmp
python3 evaluation.py -i ${ID}k_proba_formatted.tmp -t YTrue_${ID}k_formatted.txt -o /results/auc_test_${ID}k.png
