#!/usr/bin/env bash
set -ex

nThreads=8
if [ $# -ne 0 ]; then
    nThreads=$1
fi

./compile.sh

./run.sh  1 ${nThreads}
./run.sh 10 ${nThreads}
./run.sh 20 ${nThreads}
./run.sh 40 ${nThreads}
./run.sh 80 ${nThreads}
